### ISSUE TITLE
Error with Myth/Auth. Not showing login page within development mode.

### ISSUE THREAD

**Issue by jozefrebjak** [nfaiz/ci4-debug-toolbar#1]
<img width="2672" alt="Snímka obrazovky 2021-07-16 o 9 46 29" src="https://user-images.githubusercontent.com/36922215/125911994-347c7780-f1aa-4b64-8365-a84a5b51ba37.png">

**Comment by nfaiz** [comment]
Thank you for reporting. [Fixed](https://github.com/nfaiz/ci4-debug-toolbar/commit/5d01210e3adbe3878296a13c18fb5c5a7755c2b2)
